package handlers

// vocab is one curriculum entry: an Italian five-letter answer plus the
// English clue shown to the player.
type vocab struct {
	Word string
	Clue string
}

// words is the beginner curriculum, in teaching order: cognates (Italian words
// an English speaker can almost guess) come first, then everyday themed
// vocabulary. The list doubles as the accepted-guess dictionary. Accented
// words (caffè, città, …) are excluded so the game sticks to plain A–Z.
var words = []vocab{
	// --- cognates & near-cognates: the gentlest on-ramp ---
	{"PIZZA", "pizza"},
	{"PASTA", "pasta"},
	{"OPERA", "opera"},
	{"RADIO", "radio"},
	{"VILLA", "villa, country house"},
	{"MUSEO", "museum"},
	{"TRENO", "train"},
	{"METRO", "subway, metro"},
	{"POSTA", "mail, post"},
	{"COSTA", "coast"},
	{"PORTO", "port, harbor"},
	{"PARCO", "park"},
	{"BANCA", "bank"},
	{"CARTA", "paper, card"},
	{"LATTE", "milk (think: latte)"},
	{"VISTA", "view, sight"},
	{"PIANO", "piano (also: floor, plan)"},
	{"TEMPO", "time, weather (think: tempo)"},
	{"FESTA", "party, festival"},
	{"FORTE", "strong (think: forte)"},
	{"PUNTO", "point, dot"},
	{"MONTE", "mount, mountain"},
	{"TORRE", "tower"},
	{"LITRO", "liter"},
	{"CENTO", "one hundred (think: cent)"},
	{"SETTE", "seven"},
	{"VENTI", "twenty"},
	{"MILLE", "one thousand"},
	{"LEONE", "lion"},
	{"TIGRE", "tiger"},
	{"ZEBRA", "zebra"},
	{"VESPA", "wasp (think: Vespa)"},
	{"RATTO", "rat"},
	{"TONNO", "tuna"},
	{"TROTA", "trout"},
	{"SALSA", "sauce"},
	{"CREMA", "cream"},
	{"TORTA", "cake (think: torte)"},
	{"OLIVA", "olive"},
	{"VIOLA", "purple, violet"},
	{"SCENA", "scene"},
	{"STILE", "style"},
	{"CALMA", "calm"},
	{"BRAVO", "good at it (bravo!)"},
	{"SANTO", "saint, holy"},
	{"PRIMO", "first (think: prime)"},
	{"PORTA", "door (think: portal)"},
	{"LIBRO", "book (think: library)"},
	{"DENTE", "tooth (think: dental)"},
	{"MENTE", "mind (think: mental)"},
	{"NOTTE", "night (think: nocturnal)"},
	{"TERRA", "earth, land (think: terrain)"},
	{"FORZA", "strength, force"},
	{"FUNGO", "mushroom (think: fungus)"},
	{"GRANO", "wheat, grain"},
	{"NERVO", "nerve"},
	{"SEGNO", "sign, mark"},
	{"SENSO", "sense, meaning"},
	{"SCALA", "staircase, ladder (think: scale)"},
	{"SCOPO", "purpose, aim (think: scope)"},
	{"REGNO", "kingdom (think: reign)"},
	{"PATTO", "pact, deal"},
	{"CONTO", "bill, account"},
	{"CORPO", "body (think: corpse)"},
	{"CORSA", "run, race (think: course)"},
	{"QUOTA", "share, quota"},
	{"RESTO", "rest, change (money)"},
	{"SUONO", "sound"},
	{"VENTO", "wind (think: vent)"},
	{"TARDI", "late (think: tardy)"},
	{"LENTO", "slow (think: lento)"},
	{"LARGO", "wide"},
	{"LUNGO", "long"},
	{"RICCO", "rich"},
	{"NUOVO", "new (think: nova)"},
	{"VUOTO", "empty (think: void)"},
	{"MORTE", "death (think: mortal)"},
	{"GUSTO", "taste (think: gusto)"},
	{"USARE", "to use"},
	{"STARE", "to stay"},
	{"MARZO", "March"},
	{"DUOMO", "cathedral (think: dome)"},
	{"FALCO", "hawk, falcon"},
	{"PALLA", "ball"},
	{"RUOTA", "wheel (think: rotate)"},
	{"SALTO", "jump (think: somersault)"},

	// --- people & family ---
	{"AMICO", "friend"},
	{"DONNA", "woman"},
	{"NONNA", "grandmother"},
	{"NONNO", "grandfather"},
	{"GENTE", "people"},
	{"LADRO", "thief"},
	{"CUOCO", "cook, chef"},

	// --- body & feelings ---
	{"TESTA", "head"},
	{"BOCCA", "mouth"},
	{"CUORE", "heart"},
	{"PIEDE", "foot"},
	{"PETTO", "chest"},
	{"PELLE", "skin, leather"},
	{"ANIMA", "soul"},
	{"AMORE", "love"},
	{"AMARE", "to love"},
	{"BACIO", "kiss"},
	{"GIOIA", "joy"},
	{"PAURA", "fear"},
	{"SOGNO", "dream"},
	{"SONNO", "sleep"},

	// --- food & drink ---
	{"ACQUA", "water"},
	{"BIRRA", "beer"},
	{"SUCCO", "juice"},
	{"CARNE", "meat"},
	{"PESCE", "fish (to eat)"},
	{"POLLO", "chicken"},
	{"BURRO", "butter"},
	{"MIELE", "honey"},
	{"AGLIO", "garlic"},
	{"ACETO", "vinegar"},
	{"PANNA", "whipped cream"},
	{"PESCA", "peach (also: fishing)"},
	{"ZUCCA", "pumpkin"},
	{"FARRO", "spelt (a grain)"},
	{"DOLCE", "sweet, dessert"},
	{"PASTO", "meal"},
	{"FORNO", "oven"},

	// --- animals ---
	{"GATTO", "cat"},
	{"MUCCA", "cow"},
	{"CAPRA", "goat"},
	{"ASINO", "donkey"},
	{"GALLO", "rooster"},
	{"CERVO", "deer"},
	{"DAINO", "fallow deer"},
	{"LEPRE", "hare"},
	{"VOLPE", "fox"},
	{"CORVO", "crow, raven"},
	{"MERLO", "blackbird"},
	{"MOSCA", "fly (the insect)"},
	{"RAGNO", "spider"},

	// --- home & everyday objects ---
	{"LETTO", "bed"},
	{"SEDIA", "chair"},
	{"PANCA", "bench"},
	{"BANCO", "desk, counter"},
	{"BAGNO", "bathroom"},
	{"TETTO", "roof"},
	{"VETRO", "glass"},
	{"PANNO", "cloth"},
	{"GONNA", "skirt"},
	{"ZAINO", "backpack"},
	{"GESSO", "chalk"},
	{"SOLDO", "coin (soldi: money)"},
	{"SPESA", "shopping, expense"},

	// --- nature & places ---
	{"CIELO", "sky"},
	{"FIORE", "flower"},
	{"FIUME", "river"},
	{"BOSCO", "woods, forest"},
	{"CAMPO", "field"},
	{"PRATO", "lawn, meadow"},
	{"COLLE", "hill"},
	{"SASSO", "stone, rock"},
	{"LEGNO", "wood (the material)"},
	{"FIENO", "hay"},
	{"FUOCO", "fire"},
	{"LAMPO", "lightning"},
	{"OMBRA", "shadow, shade"},
	{"MONDO", "world"},
	{"LUOGO", "place"},
	{"POSTO", "place, seat"},
	{"PONTE", "bridge"},
	{"BARCA", "boat"},
	{"MEZZO", "half, middle"},

	// --- actions, games & qualities ---
	{"GIOCO", "game"},
	{"BALLO", "dance"},
	{"CANTO", "song, singing"},
	{"MOSSA", "move (in a game)"},
	{"SFIDA", "challenge"},
	{"COLPO", "hit, blow"},
	{"PALCO", "stage"},
	{"AVERE", "to have"},
	{"UDIRE", "to hear"},
	{"BELLO", "beautiful"},
	{"BUONO", "good"},
	{"CALDO", "hot, warm"},
	{"BASSO", "short, low"},
	{"CORTO", "short (in length)"},
	{"MAGRO", "thin, skinny"},
	{"PIENO", "full"},
	{"ROSSO", "red"},
	{"VERDE", "green"},
	{"FURBO", "clever, sly"},
	{"TUTTO", "everything, all"},
	{"DIECI", "ten"},
	{"VOLTA", "time, occasion"},
	{"VOLTO", "face"},
}

var wordSet = func() map[string]bool {
	m := make(map[string]bool, len(words))
	for _, v := range words {
		m[v.Word] = true
	}
	return m
}()

var clues = func() map[string]string {
	m := make(map[string]string, len(words))
	for _, v := range words {
		m[v.Word] = v.Clue
	}
	return m
}()
